name: Test

on:
  push:
  pull_request:
  
jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository
      uses: actions/checkout@v4

    - run: make test       
