name: Test

on:
  push:
  pull_request:
  
jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository
      uses: actions/checkout@v4

    - run: make test
    - run: (grep -s FAIL build/results || exit 0) && exit 1
